version: '3.1'

services:

    db:
        image: postgres:13-alpine
        ports:
            - "5434:5432"
        restart: always
        environment:
            POSTGRES_PASSWORD: postgres
        volumes:
            - 'pgsql:/var/lib/postgresql'

volumes:
    pgsql:
        driver: local